config/routes.rb
Rails.application.routes.draw do

  get 'events/whatwedo' => 'events#whatwedo'

  get 'events/team' => 'events#team'
  
  root 'events#index'
  
  resources :events do
    resources :tickets, :only => [:show, :update]
    resources :results, :only => [:index, :create]
  end

  resources :sessions, :only => [:index, :new]

  get 'auth/:provider/callback' => 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/event.rb
require 'open-uri'
require 'json'
include Slug

class Event < ActiveRecord::Base
  has_one :user
  has_many :tickets

  validates_presence_of :name
  validates_presence_of :date, :message => 'must be DD-MM-YYYY format'

  def name_normalizer
    self.name.gsub(' ', '+')
  end

  def date_normalizer
    month = self.date.strftime('%b').downcase
    date = self.date.strftime('%d')
    "#{month}+#{date}"
  end

  def get_seatgeek_info
    url = "http://api.seatgeek.com/2/events?q=#{self.name_normalizer}+on+#{self.date_normalizer}"
    results = JSON.load(open(url))
  end

  def get_seatgeek_results_total
    self.get_seatgeek_info['meta']['total']
  end

  def get_seatgeek_results
    self.get_seatgeek_info["events"].each do |e|
      # if e['venue']['country'] == 'US'
        self.tickets.create(
          :title =>  e["title"],
          :url => e["url"],
          :img_url => e['performers'].first['image'],
          :address => e['venue']['address'] + '/' + e['venue']['extended_address'],
          :date => DateTime.parse(e["datetime_local"]),
          :venue_name => e["venue"]["name"],
          :venue_loc => e["venue"]["display_location"],
          :lat => e["venue"]["location"]["lat"],
          :long => e["venue"]["location"]["lon"]
          )
      # end
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def whatwedo
  end

  def team
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save && @event.get_seatgeek_results_total > 0
      @event.get_seatgeek_results
      redirect_to @event
    elsif @event.save
      flash.now[:notice] = 'No results found'
      render :new
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    if @event.get_seatgeek_results_total > 0
      @event.get_seatgeek_results
      redirect_to @event
    else
      flash.now[:notice] = 'No results found'
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @tickets = @event.tickets
  end

  private
    def event_params
      params.require(:event).permit(:name, :date)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/home.html.erb
<!-- ==============================================
SERVICES
=============================================== -->
<section id="services" class="gray-bg padding-top">

  <div class="container">
    
    <h1 class="section-title">Welcome to Plan 4 Me</h1>
    <p class="section-description">We help you plan around your ticketed event.<br/> Suggesting restaurants, nightlife, and sights nearby!</p>
    
    <div class="row services">
    
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-right d1">
    
        <div class="icon"><i class="fa fa-search"></i></div>
        <h3>Find your event</h3>
        <p>Search for your event by entering its name and date.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-right">
    
        <div class="icon"><i class="fa fa-check"></i></div>
        <h3>Confirm your event</h3>
        <p>From the results received via SeatGeek.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-left">
    
        <div class="icon"><i class="fa fa-cutlery"></i></div>
        <h3>Make your itinerary</h3>
        <p>With results provided from Yelp and FourSquare.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-left d1">
    
        <div class="icon"><i class="fa fa-calendar"></i></div>
        <h3>Save your plans!</h3>
        <p>By exporting it to your Google Calendar.</p>
        
      </div>
      
    </div>
    
    <p class="text-center">
      <%= link_to new_event_path, :method => 'get', :class => 'btn btn-quattro scrollto' do %>Let's Start
      <% end %>
    </p>
    
  </div>
  
</section>

app/views/events/index.html.erb
<!-- ==============================================
HEADER
=============================================== -->
<header id="home" class="parallax-bg" data-parallax-background=<%= image_path "planner.jpg"%> data-stellar-background-ratio=".3">
  
  <div class="header-content">
    
    <!-- <%#= link_to root_path, :method => 'get', :class => 'header-logo' do %><i class="fa fa-angle-down">Plan 4 Me</i> -->
    <%# end %>
  
    <div class="flexslider header-slider" data-speed = '3000'>
    
      <ul class="slides">
      
        <li><h1 class="bordered-text">Welcome to <span class="primary">Plan 4 Me</span></h1></li>
        <li><h1 class="bordered-text"><span class="primary">Locate </span>Your Event</h1></li>
        <li><h1 class="bordered-text">Select <span class="primary">Nearby </span>Places</h1></li>
        <li><h1 class="bordered-text">Plan <span class="primary">Your Day</span></h1></li>
        
      </ul>
      
    </div><!--End home-slider -->
    
    <%= link_to events_whatwedo_path, :method => 'get', :class => 'scroll-button scrollto' do %>
      <i class="fa fa-hand-o-right"></i>
      <% end %>
      
  </div>
  
</header><!--End header -->

app/views/events/new.html.erb
<!-- ==============================================
    ABOUT
=============================================== -->
<section id="about" class="parallax-bg padding-top-bottom cta-image" data-parallax-background="<%= image_path "light-abstract.jpg"%>" data-stellar-background-ratio=".3">     
  <div class="container">

    <h1 class="section-title">Going Somewhere?</h1>

    <p class="section-description">Lookup your ticketed event <i class="fa fa-ticket"></i><br/></p>

    <div class="row">
      <div class="col-sm-3">
      </div>
      <div class="col-sm-6 scrollimation fade-up">
        
        <div class='notice'><%= flash[:notice] %></div>
        
        <%= bootstrap_form_for @event, :id => 'contact-form', :class => "col-sm-8 col-sm-offset-2", :html => {:novalidate => 'novalidate'} do |f| %>

          <div class="form-group">
              <%= f.text_field :name, :label => 'Event Name', :placeholder => 'Search by event name', :class => 'form-control input-lg', :"data-error-empty" => 'Please enter ticket event name', :required => true, :onfocus => "this.placeholder = ''" %>
          </div>

        <div class="form-group">
            <%= f.text_field :date, :label => 'Event Date', :class => 'form-control input-lg datepicker dp', :'data-behaviour' => 'datepicker', :placeholder => 'DD-MM-YYYY', :required => true, :onfocus => "this.placeholder = ''" %>
        </div>

        <div class="text-center">
        <%= f.submit 'Search', :class => 'btn btn-quattro', :'data-error-message' => "Error!" %>
        </div>
        <% end %>
      </div>

      <div class="col-sm-3">
      </div>
    
      
    </div><!--End row-->
    
  </div><!--End container -->
  
</section><!--End Call to Action -->

app/views/events/show.html.erb
<!-- ==============================================
PRICES
=============================================== -->
<section id="pricing" class="gray-bg padding-top-bottom">

  <div class="container">
    
    <h1 class="section-title">Confirm your ticket</h1>
    <p class="section-description">via: SeatGeek results</p>
    
    <% @tickets.each_slice(3) do |tickets| %>  
      
      <div class="row pricing">
        <div class="col-lg-10 col-lg-offset-1">
          
          <% tickets.each do |ticket| %>
            <div class="col-sm-4 text-center scrollimation fade-in">
            
              <div class="item">
                <p class="icon"><i class="fa fa-ticket fa-fw"></i></p>

                <h4><%= ticket[:title] %></h4>
            
                <h5><%= ticket.date_display %> at <%= ticket.time %></h5>

                <h5><%= ticket[:venue_name] %> - <%= ticket[:venue_loc] %></h5>

                <%= link_to 'Confirm', event_ticket_path(@event.id, ticket), :method => 'patch', :class => 'btn btn-quattro' %>
              </div>
            <%# end %>
            
            </div>
         <% end %>

         </div>
      </div><br/>
    
    <% end %>
     
  </div>
  
</section>

app/views/events/team.html.erb
    <!-- ==============================================
    TEAM
    =============================================== -->
    <section id="team-part" class="gray-bg padding-top-bottom">

      <div class="container">

        <h1 class="section-title">Meet the Team</h1>
        <p class="section-description">We are a small team with great skills. See the faces behind the lines of code. </p>

        <div class="row">

          <div class="col-md-3 col-sm-6 team-member scrollimation fade-up d1">



          </div>

          <div class="col-md-3 col-sm-6 team-member scrollimation fade-up d1">

            <div class="member-thumb">
              <%= image_tag "team/sofia-ma.jpg", class:"img-responsive img-image", alt:"" %>

              <ul class="member-socials">
                <li><a href="mailto:mail@example.com"><i class="fa fa-envelope fa-fw"></i></a></li>
                <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
                <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
                <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
              </ul>

            </div>

            <div class="member-details">
              <h4>Sofia Ma</h4>
              <p class="title">Web Developer</p>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            </div>

          </div>

          <div class="col-md-3 col-sm-6 team-member scrollimation fade-up">

            <div class="member-thumb">
              <%= image_tag "team/mike-dorfman.jpg", class:"img-responsive img-image", alt:"" %>

              <ul class="member-socials">
                <li><a href="mailto:mdorf85@gmail.com"><i class="fa fa-envelope fa-fw"></i></a></li>
                <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
                <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
                <li><a href="http://www.linkedin.com/in/michaeldorfman"><i class="fa fa-linkedin fa-fw"></i></a></li>
              </ul>

            </div>

            <div class="member-details">
              <h4>Mike Dorfman</h4>
              <p class="title">Web Developer</p>
              <p>Coder extraordinaire and graduate of Ruby-006 at The Flatiron School.</p>
            </div>

          </div>

          <div class="col-md-3 col-sm-6 team-member scrollimation fade-up d1">

          </div>

        </div>

      </div>

    </section>

app/views/events/whatwedo.html.erb
<!-- ==============================================
SERVICES
=============================================== -->
<section id="services" class="gray-bg padding-top">

  <div class="container">
    
    <h1 class="section-title">What We Do</h1>
    <p class="section-description">We help you plan around your ticketed event.<br/> Suggesting restaurants, nightlife, and sights nearby!</p>
    
    <div class="row services">
    
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-right d1">
    
        <div class="icon"><i class="fa fa-search"></i></div>
        <h3>Find your event</h3>
        <p>Search for your event by entering its name and date.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-right">
    
        <div class="icon"><i class="fa fa-check"></i></div>
        <h3>Confirm your event</h3>
        <p>From the results received via SeatGeek.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-left">
    
        <div class="icon"><i class="fa fa-cutlery"></i></div>
        <h3>Make your itinerary</h3>
        <p>With results provided from Yelp and FourSquare.</p>
        
      </div>
      
      <div class="col-md-3 col-sm-6 item text-center scrollimation fade-left d1">
    
        <div class="icon"><i class="fa fa-calendar"></i></div>
        <h3>Save your plans!</h3>
        <p>By exporting it to your Google Calendar.</p>
        
      </div>
      
    </div>
    
    <p class="text-center">
      <%= link_to new_event_path, :method => 'get', :class => 'btn btn-quattro scrollto' do %>Let's Start !
      <% end %>
    </p>
    
  </div>
  
</section>