config/routes.rb
Rails.application.routes.draw do

  get 'events/whatwedo' => 'events#whatwedo'

  get 'events/team' => 'events#team'
  
  root 'events#index'
  
  resources :events do
    resources :tickets, :only => [:show, :update]
    resources :results, :only => [:index, :create]
  end

  resources :sessions, :only => [:index, :new]

  get 'auth/:provider/callback' => 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/_footer.html.erb
<!-- ==============================================
FOOTER
=============================================== --> 
<footer id="main-footer">

  <div class="container text-center">
  
    <%#= image_tag "logo-black.png", class:"img-responsive img-center footer-logo", alt:"" %>
  
    <ul class="social-links">
      <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
      <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
      <li><a href="#link"><i class="fa fa-google-plus fa-fw"></i></a></li>
      <li><a href="#link"><i class="fa fa-dribbble fa-fw"></i></a></li>
      <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
    </ul>
    <p>&copy;2014  Made by <a href="https://http://flatironschool.com/" target="_blank">Flatiron School</a> Students</p>
    
  </div>
  
</footer>

app/views/layouts/_nav.html.erb
<!-- ==============================================
MAIN NAV
=============================================== -->

<div id="main-nav" class="navbar">
  <div class="container">
  
    <div class="navbar-header">
    
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
      
      <!-- ======= LOGO ========-->
      <a class="navbar-brand scrollto" href="#home">
        <%= link_to 'Plan 4 Me', root_path, :class => 'navbar-brand' %>
      </a>
      
    </div>
    
    <div id="site-nav" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="sr-only">
          <a href="#home" class="scrollto">Home</a>
        </li>
        <li>
          <%= link_to 'What We Do', events_whatwedo_path %>
        </li>
        <li>
          <%= link_to 'Team', events_team_path %>
        </li>
      </ul>
    </div><!--End navbar-collapse -->
    
  </div><!--End container -->
  
</div><!--End main-nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>

  <!-- ==============================================
    Title and Meta Tags
    =============================================== -->
    <meta charset="utf-8">
    <title>Plan 4 Me</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- ==============================================
    Favicons
    =============================================== -->
    <link rel="shortcut icon" href="assets/images/favicon.ico">
    <link rel="apple-touch-icon" href="assets/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="assets/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="assets/images/apple-touch-icon-114x114.png">

    <!-- ==============================================
    Fonts
    =============================================== -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,100italic,400,300italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
</head>
<body data-spy="scroll" data-target="#main-nav" data-offset="400">
    <!--=== PAGE PRELOADER ===-->
    <div id="page-loader"><span class="page-loader-gif">Loading...</span></div>
  
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

</body>
</html>